# Generated by Django 2.2.4 on 2022-10-26 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20221026_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web_app.User'),
        ),
    ]
